# Generated by Django 4.2.17 on 2025-01-10 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': (('can_publish_article', 'Can publish article'), ('can_edit_article', 'Can edit article'))},
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('failed', '支付失败')], max_length=20)),
                ('shipping_address', models.TextField()),
                ('shipping_status', models.CharField(choices=[('not_shipped', '未发货'), ('shipped', '已发货'), ('delivered', '已送达'), ('returned', '已退回')], max_length=20)),
                ('order_notes', models.TextField(blank=True, null=True)),
                ('thug', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('single_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='orders/')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_received', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('manual_status', models.BooleanField(default=False)),
                ('audit_status', models.CharField(choices=[('pending', '待审核'), ('approved', '已审核通过'), ('rejected', '已审核拒绝')], default='pending', max_length=20)),
                ('boss', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_orders', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['-order_date'],
            },
        ),
    ]
