# Generated by Django 4.2.17 on 2025-01-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0003_remove_order_order_notes_remove_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='boss',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
