# Generated by Django 4.2.17 on 2025-01-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0004_alter_order_boss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='single_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
