# Generated by Django 4.2.17 on 2025-01-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0005_alter_order_single_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_closed',
            field=models.CharField(choices=[('yes', '是'), ('no', '否')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_received',
            field=models.CharField(choices=[('yes', '是'), ('no', '否')], default='no', max_length=3),
        ),
    ]
