# Generated by Django 4.2.17 on 2025-01-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0006_alter_order_is_closed_alter_order_is_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='manual_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
