# Generated by Django 4.2.17 on 2025-01-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0007_alter_order_manual_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='image',
        ),
        migrations.AddField(
            model_name='order',
            name='image_paths',
            field=models.TextField(blank=True, null=True),
        ),
    ]
